### ISSUE TITLE
Creating and Using Containers Like a Boss

### ISSUE THREAD

**Issue by itschunv** [chariot9/blog#2]
### Why?
- Deeper understanding of docker
### What?
- Docker

**Comment by itschunv** [comment]
Running docker container in background:
```bash
--detach
```

**Comment by itschunv** [comment]
Specific docker container name:
```bash
--name
```

**Comment by itschunv** [comment]
Check log:
```bash
docker container logs <name>
```

**Comment by itschunv** [comment]
remove container:
```bash
docker container rm <id>
```

**Comment by itschunv** [comment]
What happens in 'docker container run'
1. Looks for that image locally in image cache, doesn't find anything
2. Then looks in remote image repository (defaults to Docker Hub)
3. Downloads the latest version (nginx:latest by default)
4. Creates new container based on that image and prepares to start
5. Gives it a virtual IP on a private network inside docker engine
6. Opens up port 80 on host and forwards to port 80 in container
7. Starts container by using the CMD in the image Dockerfile

**Comment by chunchun02** [comment]
List up processes inside the containers:
```bash
docker container top <name>
```

**Comment by chunchun02** [comment]
Show live performance data for all containers:
```bash
docker stats <name>
```

**Comment by itschunv** [comment]
What's Going On In Containers:

• docker container top - process list in one container
• docker container inspect - details of one container config
• docker container stats - performance stats for all containers

**Comment by itschunv** [comment]
Docker Networks: CLI Management

• Show networks docker network ls
• Inspect a network docker network inspect
• Create a network docker network create --driver
• Attach a network to container docker network connect
• Detach a network from container docker network disconnect
